chat/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("Homepage/", chatHomepage,name ='chatHomepage'),  
    path("chat/<name>",get_or_create_chatroom,name="start_chat"),
    path('chat/room/<chatroom_name>',chatHomepage,name="chatroom"),
    path('chat/new_groupchat/',create_groupchat,name="new-groupchat"),
    path('chat/edit/<chatroom_name>',chatroom_edit_view,name="edit-chatroom"),
    path('chat/delete/<chatroom_name>',chatroom_delete_view,name="chatroom-delete"),
    path('chat/leave/<chatroom_name>',chatroom_leave_view, name='chatroom-leave'),
    path('chat/fileupload/<chatroom_name>',chat_file_upload,name="chat-file-upload")
]

chatapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404
from django.shortcuts import render

# Function to handle 404 errors
def custom_404_view(request, exception):
    return render(request, '404.html', status=404)

# Setting the handler
handler404 = custom_404_view

# URL patterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('chats/', include('chat.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.core.validators import FileExtensionValidator
from django.templatetags.static import static
import shortuuid
import os
import pytz
from PIL import Image


class ChatGroup(models.Model):
    group_name = models.CharField(max_length=128, unique=True, default=shortuuid.uuid)
    groupchat_name = models.CharField(max_length=128, null=True, blank=True)
    admin = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='groupChats', null=True, blank=True, on_delete=models.SET_NULL)
    users_online = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="online_in_groups", blank=True)
    members = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='chat_groups', blank=True)
    is_private = models.BooleanField(default=False)
    group_image = models.ImageField(upload_to='group_images/', null=True, blank=True, validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])
    last_activity = models.DateTimeField(default=timezone.now)

    def update_last_activity(self):
        self.last_activity = timezone.now()
        self.save()

    def get_formatted_last_activity(self):
        india_tz = pytz.timezone('Asia/Kolkata')
        last_activity_local = self.last_activity.astimezone(india_tz)
        now = timezone.now().astimezone(india_tz)
        
        days_difference = (now.date() - last_activity_local.date()).days

        if days_difference == 0:
            # If the message is from today, show the exact time
            return last_activity_local.strftime("%I:%M %p").lower().lstrip('0')
        elif days_difference == 1:
            # If the message is from yesterday, show "Yesterday"
            return "Yesterday"
        elif days_difference == 2:
            # If the message is from the day before yesterday, show "Day before yesterday"
            return last_activity_local.strftime("%A")
        elif 2 < days_difference < 7:
            # If the message is from earlier this week (but not yesterday or day before), show the day name
            return last_activity_local.strftime("%A")
        else:
            # For messages a week old or older, show the date
            return last_activity_local.strftime("%d %b %Y")

    def __str__(self):
        return self.groupchat_name or self.group_name
    
    @property
    def avatar(self):
        if self.group_image:
            return self.group_image.url
        return static('images/grp-icon.jpg')
    
    

class GroupMessage(models.Model):
    group = models.ForeignKey(ChatGroup, related_name='chat_messages', on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    body = models.CharField(max_length=300, blank=True, null=True)
    file = models.FileField(upload_to='files/', blank=True, null=True)

    created = models.DateTimeField(auto_now_add=True)

    def get_formatted_time(self):
        india_tz = pytz.timezone('Asia/Kolkata')
        india_time = self.created.astimezone(india_tz)
        return india_time.strftime("%I:%M %p").lower().lstrip('0')
    
    @property
    def filename(self):
        if self.file:
            return os.path.basename(self.file.name)
        return None

    def __str__(self):
        if self.body:
            return f'{self.author.name} : {self.body}'
        elif self.file:
            return f'{self.author.name} : {self.filename}'

    class Meta:
        ordering = ['-created']

    @property    
    def is_image(self):
        try:
            image = Image.open(self.file) 
            image.verify()
            return True 
        except:
            return False
    
    

        

chat/forms.py
from django.forms import ModelForm
from django import forms
from .models import *


class ChatmessageCreateForm(ModelForm):
    body = forms.CharField(label='', widget=forms.TextInput(attrs={
        'placeholder': 'Add message ...',
        'class': 'p-4 text-black',
        'maxlength': '300',
        'autofocus': True,
        'style': 'width: 1000px;'
    }))

    class Meta:
        model = GroupMessage
        fields = ['body']

class NewGroupForm(forms.ModelForm):
    class Meta:
        model = ChatGroup
        fields = ['groupchat_name', 'group_image']
        widgets = {
            'groupchat_name': forms.TextInput(attrs={
                'class': 'w-full px-3 py-2 border border-gray-300 rounded-md mt-2 mb-2',
                'max_length': '300',
                'placeholder': 'Enter group chat name',
            }),
            'group_image': forms.ClearableFileInput(attrs={
                'class': 'w-full px-3 py-2 border border-gray-300 rounded-md mt-2 mb-2',
                'accept': 'image/*'
            }),
        }

class ChatRoomEditForm(forms.ModelForm):
    group_image = forms.ImageField(
        label='Group Image',
        required=False,
        widget=forms.FileInput(attrs={
            'class': 'w-full px-3 py-2 border border-gray-300 rounded-md mt-6',
            'accept': 'image/*'
        })
    )

    class Meta:
        model = ChatGroup
        fields = ['groupchat_name', 'group_image']
        widgets = {
            'groupchat_name': forms.TextInput(attrs={
                'class': 'w-full px-3 py-2 border border-gray-300 rounded-md',
                'max_length': '300',
                'placeholder': 'Enter group chat name',
            }),
        }

chat/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import ChatGroup, GroupMessage
from django.contrib.auth.decorators import login_required
from django.http import Http404
from asgiref.sync import async_to_sync
from django.http import HttpResponse
from .forms import *
from django.contrib.auth import get_user_model
from django.contrib import messages
from channels.layers import get_channel_layer


@login_required
def chatHomepage(request, chatroom_name='public-chat'):
    profile = request.user.profile
    chat_group = get_object_or_404(ChatGroup, group_name=chatroom_name)
    
    chat_messages = chat_group.chat_messages.all()[:30]
    form = ChatmessageCreateForm()

    other_user = None
    if chat_group.is_private:
        if request.user not in chat_group.members.all():
            chat_group.members.add(request.user)  # Allow rejoining for private groups
        members = chat_group.members.all()
        for member in members:
            if member != request.user:
                other_user = member
                break

    if not chat_group.is_private:
        if request.user not in chat_group.members.all():
            chat_group.members.add(request.user)

    for group in request.user.chat_groups.all():
        if not group.groupchat_name:
            group.groupchat_name = group.group_name
            group.save()

    chat_groups = request.user.chat_groups.all().order_by('-last_activity')

    # Debugging Output
    print("Other User:", other_user)
    print("Chat Group Members:", chat_group.members.all())

    if request.htmx:
        form = ChatmessageCreateForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.author = request.user
            message.group = chat_group
            message.save()
            
            chat_group.update_last_activity()

            context = {
                'chat_messages': chat_messages,
                'user': request.user
            }
            return render(request, 'partials/chat_message_p.html', context)
        
    context = {
        'chat_messages': chat_messages,
        'form': form,
        'other_user': other_user,
        'chatroom_name': chatroom_name,
        'chat_group': chat_group,
        'profile': profile,
        'chat_groups': chat_groups, 
    }
    return render(request, 'chatHomepage.html', context)




@login_required
def get_or_create_chatroom(request, name):
    profile = request.user.profile
    if request.user.name == name:
        return redirect('home')
    
    User = get_user_model()
    other_user = User.objects.get(name=name)
    my_chatrooms = request.user.chat_groups.filter(is_private=True)
    
    chatroom = None
    if my_chatrooms.exists():
        for room in my_chatrooms:
            if other_user in room.members.all():
                chatroom = room
                break
    
    if not chatroom:
        chatroom = ChatGroup.objects.create(is_private=True)
        chatroom.members.add(other_user, request.user)
    else:
        chatroom.members.add(request.user)  # Allow rejoining by adding the user back to the group

    return redirect('chatroom', chatroom_name=chatroom.group_name)



@login_required
def create_groupchat(request):
    profile = request.user.profile
    form  = NewGroupForm()
    if request.method == 'POST':
        form = NewGroupForm(request.POST,request.FILES)
        if form.is_valid():
            new_groupchat = form.save(commit=False)
            new_groupchat.admin = request.user
            new_groupchat.save()
            new_groupchat.members.add(request.user)
            return redirect('chatroom',new_groupchat.group_name)
    context = {
        'form': form,
        'profile': profile

    }
    return render(request,'create_groupchat.html',context)


from django.contrib.auth import get_user_model

@login_required
def chatroom_edit_view(request, chatroom_name):
    profile = request.user.profile
    chat_group = get_object_or_404(ChatGroup, group_name=chatroom_name)
    if request.user != chat_group.admin:
        raise Http404()

    form = ChatRoomEditForm(instance=chat_group)
    if request.method == 'POST':
        form = ChatRoomEditForm(request.POST, request.FILES, instance=chat_group)
        if form.is_valid():
            form.save()

            remove_members = request.POST.getlist('remove_members')
            User = get_user_model()
            for member_id in remove_members:
                try:
                    member = User.objects.get(id=member_id)
                    chat_group.members.remove(member)
                    if chat_group.group_name == 'public-chat':
                        member.profile.removed_from_public = True
                        member.profile.save()
                except User.DoesNotExist:
                    print(f"User with ID {member_id} does not exist.")

            return redirect('chatroom', chatroom_name)
        else:
            print(form.errors)  # Print form errors if the form is not valid

    # Fetch all members of the chat group
    members = chat_group.members.all().select_related('profile')

    context = {
        'form': form,
        'chat_group': chat_group,
        'members': members,
        'profile': profile
    }
    return render(request, 'chatroom_edit.html', context)




@login_required
def chatroom_delete_view(request,chatroom_name):
    profile = request.user.profile
    chat_group = get_object_or_404(ChatGroup,group_name=chatroom_name)
    print("chatgroup:",chat_group)
    if request.user != chat_group.admin:
        raise Http404()
    
    if request.method == 'POST':
        chat_group.delete()
        messages.success(request,'Chatroom deleted successfully')
        return redirect('chatHomepage')
    context = {
        'profile':profile,
        'chat_group':chat_group,
    }
    return render(request,'chatroom_delete.html',context)

@login_required
def chatroom_leave_view(request, chatroom_name):
    chat_group = get_object_or_404(ChatGroup, group_name=chatroom_name)
    if request.user not in chat_group.members.all():
        raise Http404()
    
    if request.method == 'POST':
        chat_group.members.remove(request.user)
        messages.success(request, 'You left the chat')
        return redirect('chatHomepage')
    
    return render(request, 'chat_exit.html', {'chat_group': chat_group})


def chat_file_upload(request,chatroom_name):
    chat_group = get_object_or_404(ChatGroup, group_name=chatroom_name)

    if request.htmx and request.FILES:
        file = request.FILES['file']
        message = GroupMessage.objects.create(
            file = file,
            author = request.user,
            group = chat_group,
        )

        channel_layer  =  get_channel_layer()
        event = {
            'type': 'message_handler',
            'message_id':message.id
        }

        async_to_sync(channel_layer.group_send)(
            chatroom_name,event
        )
    return HttpResponse

chat/templates/chatHomepage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="bg-gray-100 h-screen flex border overflow-hidden">
    <!-- Sidebar -->
    {% include 'chat_sidebar.html' %}
    
    <!-- Main Area -->
    <main class="flex-1 flex flex-col h-screen overflow-hidden">
        <!-- Default View -->
        <div id="default-view" class="flex-1 flex items-center justify-center bg-gray-50" style="display: none;">
            <div class="text-center">
                <img src="{% static 'images/chat-box.png' %}" alt="Chatify" class="w-72 h-72 mx-auto mb-4">
                <h2 class="text-2xl font-semibold text-gray-700">Welcome to Chatify</h2>
                <p class="text-gray-500 mt-2">Select a chat to start messaging</p>
            </div>
        </div>

        <!-- Chat View (Initially Hidden) -->
        <div id="chat-view" class="hidden flex flex-col h-full">
            <!-- Header - Fixed -->
            {% include 'chat_header.html' %}

            <!-- Messages - Scrollable -->
            <div id="chat_messages" class="flex-1 overflow-y-auto p-4 space-y-4 list-none bg-gray-50">
                {% for message in chat_messages reversed %}
                {% include 'chat_message.html' %}
                {% endfor %}
            </div>

            <footer class="bg-white border-t border-gray-200 p-2 flex-none">
                <!-- File Upload Form (Initially Hidden) -->
                <form id="chat_file_form" enctype="multipart/form-data" class="hidden flex items-center w-full mb-2"
                    hx-post="{% url 'chat-file-upload' chat_group.group_name %}"
                    x-target="#chat_messages"
                    hx-swap="beforeend"
                    _="on htmx:beforeSend reset() me">
                    {% csrf_token %}
                    <label for="id_file" class="cursor-pointer flex items-center">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.172 7l-6.586 6.586a2 2 0 102.828 2.828l6.414-6.586a4 4 0 00-5.656-5.656l-6.415 6.585a6 6 0 108.486 8.486L20.5 13" />
                        </svg>
                        <!-- Hidden file input -->
                        <input type="file" name="file" id="id_file" class="hidden" onchange="displayFileName()">
                    </label>
                    <!-- Span to display the selected file name -->
                    <span id="file-name" class="ml-2 text-sm text-gray-500">No file selected</span>
                    <button type="submit" id="upload-button" class="bg-indigo-600 text-white px-3 py-1 rounded-lg shadow-lg transition-all cursor-pointer ml-2 text-sm hidden">Upload File</button>
                </form>
            
                <!-- Chat Message Form -->
                <form id="chat_message_form" class="flex items-center w-full mb-20"
                    hx-ext="ws"
                    ws-connect="/ws/chatroom/{{chatroom_name}}"
                    ws-send
                    _="on htmx:wsAfterSend reset() me">
                    {% csrf_token %}
                    {{ form }}
                    <button type="submit" class="bg-indigo-600 text-white px-4 py-2 rounded-lg shadow-lg transition-all cursor-pointer ml-2">Send</button>
                    <!-- + Icon to Show File Upload Form -->
                    <button type="button" id="toggle-file-form" class="text-gray-500 px-2 py-1 rounded-lg transition-all cursor-pointer ml-2">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
                        </svg>
                    </button>
                </form>
            </footer>
        </div>
    </main>
</div>

<script>
    function scrollToBottom(time = 0) {
        setTimeout(function () {
            const messagesContainer = document.getElementById('chat_messages');
            messagesContainer.scrollTop = messagesContainer.scrollHeight;
        }, time);
    }

    function showChat(chatId) {
        const defaultView = document.getElementById('default-view');
        const chatView = document.getElementById('chat-view');
        
        if (defaultView && chatView) {
            defaultView.style.display = 'none';  // Hide default view
            chatView.classList.remove('hidden'); // Show chat view
            loadChatMessages(chatId);
            scrollToBottom();
        } else {
            console.error('One or more view elements not found');
        }
    }

    function hideChat() {
        const defaultView = document.getElementById('default-view');
        const chatView = document.getElementById('chat-view');
        
        if (defaultView && chatView) {
            defaultView.style.display = 'flex';  // Show default view
            chatView.classList.add('hidden');    // Hide chat view
        } else {
            console.error('One or more view elements not found');
        }
    }

    function handleUrlChange() {
        const path = window.location.pathname;
        const match = path.match(/^\/chats\/chat\/room\/([^/]+)/);
        
        if (match) {
            const chatId = match[1];
            showChat(chatId);
        } else {
            hideChat();
        }
    }

    window.addEventListener('popstate', handleUrlChange);
    document.addEventListener('DOMContentLoaded', handleUrlChange);

    function loadChatMessages(chatId) {
        console.log(`Loading messages for chat ${chatId}`);
    }

    function displayFileName() {
        var fileInput = document.getElementById('id_file');
        var fileName = document.getElementById('file-name');
        var uploadButton = document.getElementById('upload-button');

        if (fileInput.files.length > 0) {
            fileName.textContent = fileInput.files[0].name;
            uploadButton.classList.remove('hidden');
        } else {
            uploadButton.classList.add('hidden');
        }
    }

    document.getElementById('toggle-file-form').addEventListener('click', function () {
        var fileForm = document.getElementById('chat_file_form');
        fileForm.classList.toggle('hidden');
    });

    document.getElementById('chat_file_form').addEventListener('submit', function (event) {
        event.preventDefault();

        var formData = new FormData(this);

        fetch(this.action, {
            method: 'POST',
            body: formData,
            headers: {
                'X-CSRFToken': document.querySelector('input[name="csrfmiddlewaretoken"]').value
            }
        })
            .then(response => {
                if (response.ok) {
                    document.getElementById('id_file').value = '';
                    document.getElementById('file-name').textContent = 'No file selected';
                    document.getElementById('upload-button').classList.add('hidden');
                } else {
                    console.error('Upload failed:', response.statusText);
                }
            })
            .catch(error => {
                console.error('Fetch error:', error);
            });
    });
</script>
{% endblock %}

chat/templates/chat_default_page.html
<!-- <div id="default-view" class="flex-1 flex items-center justify-center bg-gray-50">
            <div class="text-center">
                <img src="https://upload.wikimedia.org/wikipedia/commons/6/6b/WhatsApp.svg" alt="WhatsApp" class="w-32 h-32 mx-auto mb-4">
                <h2 class="text-2xl font-semibold text-gray-700">Welcome to WhatsApp Web</h2>
                <p class="text-gray-500 mt-2">Select a chat to start messaging</p>
            </div>
        </div> -->

chat/templates/chat_exit.html
{% extends 'base.html' %}
{% block content%}

<content class="block max-w-3xl mx-auto md:p-12">
    <div class="bg-white rounded-2xl md:drop-shadow-2xl shadow-black w-full p-8">

        <div>
            <h1 class="text-3xl font-bold mb-4">Leave Chatroom</h1>
            <h2>"{{chat_group.groupchat_name }}"</h2>
            <p class="text-gray-600 mb-8">Are you sure you want to Leave chatGroup?</p>
        </div>

        <form method='POST' class="space-y-4">
            {% csrf_token %}
            <div class="flex flex-col sm:flex-row sm:space-x-4 space-y-4 sm:space-y-0">
                <button type="submit" class="w-full sm:w-auto flex justify-center py-3 px-6 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500">
                    Exit Group
                </button>
                <a href="{{ request.META.HTTP_REFERER }}" class="w-full sm:w-auto flex justify-center py-3 px-6 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                    Cancel
                </a>
            </div>
        </form>
    </div>
</content>
{%endblock%}

chat/templates/chat_header.html
{% load static%}
{% block content %}
<header class="p-3 flex-none bg-white border-b border-gray-200">
    <div class="flex justify-between items-center">
        <div class="flex flex-row items-center space-x-4 overflow-hidden">
            {% if other_user %}
                <a href="{% url 'profile' other_user.name %}" class="flex items-center space-x-2 flex-shrink-0">
                    <div class="relative">
                        {% if other_user in chat_group.users_online.all %}
                            <div class="absolute rounded-full bg-green-500 p-1.5 border-2 border-gray-200 bottom-0 right-0"></div>
                        {% else %}
                            <div class="absolute rounded-full bg-gray-500 p-1.5 border-2 border-gray-200 bottom-0 right-0"></div>
                        {% endif %}
                        <img class="w-10 h-10 rounded-full border border-gray-200 object-cover" src="{{ other_user.profile.avatar }}" alt="{{ other_user.profile.name }}" />
                    </div>
                    <div class="flex flex-col">
                        <span class="font-semibold text-black">{{ other_user.profile.name }}</span> 
                        <span class="text-sm font-light text-gray-400">@{{ other_user.name }}</span>
                    </div>
                </a>
            {% elif chat_group.groupchat_name %}
                <div class="flex items-center flex-shrink-0">
                    {% if chat_group.group_image %}
                        <img src="{{ chat_group.avatar}}" alt="group icon" class="w-10 h-10 rounded-full border border-gray-200 object-cover">
                    {% endif %}
                    <div class="ml-2">
                        <div class="flex justify-between">
                        <h2 class="text-lg text-slate-600 font-semibold">{{ chat_group.groupchat_name }}</h2>
                        {%if user == chat_group.admin %}
                        <a href="{% url 'edit-chatroom' chat_group.group_name %}">
                            <div class="p-2  rounded-lg transition-colors">
                                <svg class="fill-gray-600" width="16" height="16">
                                    <path d="M11.013 1.427a1.75 1.75 0 0 1 2.474 0l1.086 1.086a1.75 1.75 0 0 1 0 2.474l-8.61 8.61c-.21.21-.47.364-.756.445l-3.251.93a.75.75 0 0 1-.927-.928l.929-3.25c.081-.286.235-.547.445-.758l8.61-8.61Zm.176 4.823L9.75 4.81l-6.286 6.287a.253.253 0 0 0-.064.108l-.558 1.953 1.953-.558a.253.253 0 0 0 .108-.064Zm1.238-3.763a.25.25 0 0 0-.354 0L10.811 3.75l1.439 1.44 1.263-1.263a.25.25 0 0 0 0-.354Z"></path>
                                </svg>
                            </div>
                        </a>
                        {%endif%}
                    </div>
                        <span id="online-count" class="text-sm text-gray-500"></span>
                        <span class="text-sm text-gray-500">online</span>
                    </div>
                    
                </div>
                <ul id="groupchat-members" class="flex flex-wrap space-x-2 overflow-hidden max-w-[200px]">
                    {% for member in chat_group.members.all %}
                        {% if member != chat_group.admin %}
                            <li class="flex-shrink-0 mb-2">
                                <a href="{% url 'profile' member.name %}" class="flex flex-col items-center justify-center w-16 text-center">
                                    <img src="{{ member.profile.avatar }}" alt="{{ member.profile.name }}" class="w-10 h-10 rounded-full object-cover mb-1"/>
                                    <span class="text-xs text-gray-400 truncate w-full">{{ member.profile.name|slice:":10" }}</span>
                                </a>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
                
            {% else %}
                <div class="flex items-center flex-shrink-0">
                    {% if chat_group.group_name %}
                        <img src="{{ chat_group.avatar }}" alt="group icon" class="w-10 h-10 rounded-full border border-gray-200 object-cover">
                    {% endif %}
                    <div class="ml-2">
                        <h2 class="text-lg text-slate-600 font-semibold">{{ chat_group.group_name }}</h2>
                        <span id="online-count" class="text-sm text-gray-500"></span>
                        <span class="text-sm text-gray-500">online</span>
                    </div>
                </div>
            {% endif %}
        </div>
        {% if chat_group.groupchat_name and chat_group.group_name != 'public-chat' and not other_user %}
        <a href="{% url 'chatroom-leave' chat_group.group_name %}" class="text-gray-400 hover:text-black transition-colors ml-4 flex-shrink-0">
            Leave Chat
        </a>
    {% endif %}
    </div>
</header>
{% endblock %}

chat/templates/chat_message.html
{% if message.author == user %}
<li class="flex justify-end mb-4">
    <div class="bg-green-200 rounded-l-lg rounded-tr-lg p-2 max-w-[75%]">
        {% include 'partials/message_content.html' %}
    </div>
    <div class="flex items-end">
        <svg height="13" width="8">
            <path fill="#bbf7d0" d="M6.3,10.4C1.5,8.7,0.9,5.5,0,0.2L0,13l5.2,0C7,13,9.6,11.5,6.3,10.4z"/>
        </svg>
    </div>
</li>
{% else %}
<li>
    <div class="flex justify-start">
        <div class="flex items-end mr-2">
            <a href="{% url 'profile' message.author.name %}">
                <img class="w-8 h-8 rounded-full object-cover" src="{{ message.author.profile.avatar }}">
            </a>
        </div>
        <div class="flex items-end">
            <svg height="13" width="8">
                <path fill="white" d="M2.8,13L8,13L8,0.2C7.1,5.5,6.5,8.7,1.7,10.4C-1.6,11.5,1,13,2.8,13z"></path>
            </svg>
        </div>
        <div class="bg-white p-2 max-w-[75%] rounded-r-lg rounded-tl-lg">
            {% include 'partials/message_content.html' %}
            <span class="text-xs text-gray-400 text-end font-mono">{{ message.get_formatted_time }}</span>
        </div>  
    </div>
    <div class="text-sm font-light py-1 ml-10">
        <span class="text-black">{{ message.author.name }}</span> 
        <span class="text-gray-400">@{{ message.author.profile.name }}</span>
        
    </div>
</li>
{% endif %}

chat/templates/chatroom_delete.html
{% extends 'base.html' %}
{% block content%}
<!-- delete chatroom
<h2>"{{chat_group.groupchat_name}}"</h2>
<form method="post">
    {%csrf_token%}
    <button type="submit" class="mt-4 bg-red-500">Yes delete</button>
    <a class="button bg-gray-300 ml-1" href="{{request.META.HTTP_REFERER}}">Cancel</a>
</form> -->

<content class="block max-w-3xl mx-auto md:p-12">
    <div class="bg-white rounded-2xl md:drop-shadow-2xl shadow-black w-full p-8">

        <div>
            <h1 class="text-3xl font-bold mb-4">Delete ChatRoom</h1>
            <h2>"{{chat_group.groupchat_name }}"</h2>
            <p class="text-gray-600 mb-8">Are you sure you want to delete your chatGroup?</p>
        </div>

        <form method='POST' class="space-y-4">
            {% csrf_token %}
            <div class="flex flex-col sm:flex-row sm:space-x-4 space-y-4 sm:space-y-0">
                <button type="submit" class="w-full sm:w-auto flex justify-center py-3 px-6 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500">
                    Yes, Delete
                </button>
                <a href="{{ request.META.HTTP_REFERER }}" class="w-full sm:w-auto flex justify-center py-3 px-6 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                    Cancel
                </a>
            </div>
        </form>
    </div>
</content>
{%endblock%}

chat/templates/create_groupchat.html
{% extends 'base.html'%}
{%block content%}
<div class="block max-w-3xl mx-auto md:p-12">
    <div class="bg-white rounded-2xl md:drop-shadow-2xl shadow-black w-full p-8">

        <h1 class="text-2xl font-bold mb-4">Create New Chat</h1>
        <form method="post" enctype="multipart/form-data">
            {%csrf_token%}
            {{form}}
        <button type="submit" class=" bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 mt-6 rounded">Create</button>
        </form>

</div>
</div>


{%endblock%}